name: temp

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - run: echo ${{ github.ref }}
      - run: echo `git branch --remotes | grep origin/rc/[0-9]* | tr -d ' ' || echo -n ""`
