name: temp

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: github.ref
        run: echo ${{ github.ref }}
      - name: github.ref_name
        run: echo ${{ github.ref_name }}
      - run: echo `git branch --remotes | tr -d ' ' || echo -n ""`
